/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mlh.goofygoofies.minecraft_rp;

// import org.junit.Test;
// import static org.junit.Assert.*;

public class LibraryTest {
    // @Test public void testSomeLibraryMethod() {
    //     MinecraftRP classUnderTest = new MinecraftRP();
    //     assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    // }
}
